#!/bin/bash

chmod -R 755 .
clear
read -p "What would you like me to post master? :: " message
git add .
git commit -m "$message"
repository_url=$(git remote get-url origin)  
# Get the repository URL
repository_name=$(basename "$repository_url" .git)  
# Extract the repository name from the URL
git push
if [ $? -eq 0 ]; then
    # Get the list of files that were committed
    committed_files=$(git diff-tree --no-commit-id --name-only -r HEAD)
    
    sleep 3
    clear
    echo "That worked master!     Too bad that you suck at coding!"
    echo "'$message' Commit message was used on GitHub repo '$repository_name'"
    echo "Changes were made to the following files:"
    echo "$committed_files"
    sleep 8
    clear
    
    # Display the changes made to each committed file and save to a text file
    for file in $committed_files; do
        echo "Changes in '$file':" > "$file_changes.txt"
        git diff HEAD^..HEAD "$file" >> "$file_changes.txt"
        echo >> "$file_changes.txt"
    done
    sleep 5

    echo "Changes saved to files: $committed_files"

    sleep 5
    clear
else
    echo "That didn't work stupid! see you suck at everything!"
    sleep 3
fi
